# Generated by Django 3.1.1 on 2020-09-06 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=70, upload_to='')),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
